name: Build

on: pull_request

jobs:
  build:
    if: ${{ github.event.label.name == 'build test' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5

      - name: Install, Build
        run: |
          npm install --legacy-peer-deps
          npm run build_clean
